export const USER_STATE_CHANGE = "USER_STATE_CHANGE";
export const USER_POSTS_STATE_CHANGE = "USER_POSTS_STATE_CHANGE";
export const USER_LOGOUT = "USER_LOGOUT";
export const USER_NEW_POST = "USER_NEW_POST";
